//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITManager.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ManagerEntities : DbContext
    {
        public ManagerEntities()
            : base("name=ManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<LanguageLevel> LanguageLevel { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<ProfessionalSkill> ProfessionalSkill { get; set; }
        public virtual DbSet<ProfessionalSummary> ProfessionalSummary { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Query> Query { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sertificate> Sertificate { get; set; }
        public virtual DbSet<SkillLevel> SkillLevel { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TechnicalGroup> TechnicalGroup { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserRoles> UserRoles { get; set; }
        public virtual DbSet<UserSkills> UserSkills { get; set; }
    }
}
