//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITManager.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ITManagerEntities : DbContext
    {
        public ITManagerEntities()
            : base("name=ITManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Education> Educations { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<LanguageLevel> LanguageLevels { get; set; }
        public virtual DbSet<LanguagesList> LanguagesLists { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<ProfessionalSkill> ProfessionalSkills { get; set; }
        public virtual DbSet<ProfessionalSummary> ProfessionalSummaries { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<Query> Queries { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sertificate> Sertificates { get; set; }
        public virtual DbSet<SkillLevel> SkillLevels { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserProject> UserProjects { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<UserSkill> UserSkills { get; set; }
    }
}
