//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITManager.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSkill
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int SkillId { get; set; }
        public int SkillLevelId { get; set; }
    
        public virtual ProfessionalSkill ProfessionalSkill { get; set; }
        public virtual SkillLevel SkillLevel { get; set; }
        public virtual User User { get; set; }
    }
}
