use ITManager;

insert into Position values ('Technical Writer');
insert into Position values ('Software Engineer');
insert into Position values ('QA Engineer/ Tester');
insert into Position values ('Project Manager');
insert into Position values ('Senior Software Engineer');
insert into Position values ('Marketing Manager (IT)');
insert into Position values ('Junior Software Engineer');
insert into Position values ('Lead Software Engineer');
insert into Position values ('Senior QA Engineer/ Tester');
insert into Position values ('Team Leader');
insert into Position values ('Junior QA Engineer/ Tester');
insert into Position values ('HTML Coder');
insert into Position values ('Business Analyst');
insert into Position values ('System Administrator');
insert into Position values ('Senior Project Manager');
insert into Position values ('QA');
insert into Position values ('Team Leader');
insert into Position values ('HR');
insert into Position values ('GUI Designer');
insert into Position values ('Web Designer');
insert into Position values ('Software Maintenance Engineer');
insert into Position values ('SEO Specialist');
insert into Position values ('Copywriter');
insert into Position values ('Support Engineer');
insert into Position values ('Department Manager');
insert into Position values ('PR Manager (IT)');
insert into Position values ('Content Manager');
insert into Position values ('Solution Architect');
insert into Position values ('Support Specialist');
insert into Position values ('Data Analyst');
insert into Position values ('Chief Technical Officer');
insert into Position values ('Data Scientist');
insert into Position values ('QA Automation Engineer');
insert into Position values ('DevOps Engineer');
insert into Position values ('Product Manager');
insert into Position values ('Solution Engineer');
insert into Position values ('System Analyst');
insert into Position values ('Solution Engineer');
insert into Position values ('Support Specialist');
insert into Position values ('3D Artist');
insert into Position values ('Support Engineer');
insert into Position values ('ETL Developer');
insert into Position values ('CTO');
insert into Position values ('Performance Analyst');
insert into Position values ('Content Manager');
insert into Position values ('Data Analyst');
insert into Position values ('Solution Architect');
insert into Position values ('Sales Manager');
insert into Position values ('Data Engineer');
insert into Position values ('Recruiter');